version: "3"
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build: ./php
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password # No need for MariaDB
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
    pma:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - mysql:mysql
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret
    postgres:
        image: postgres:12
        restart: always
        environment:
            PGSQL_ROOT_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    phppgadmin:
        image: neimheadh/phppgadmin:latest
        ports:
        - "88:80" # web browsers block the port 100080. Use 8080 instead.
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASS: password
volumes:
  pgdata: